"use client";
import { useMemo, useState } from "react";
import { BarChart3, CheckCircle2, Clock3, Download, Gauge, Leaf, Lightbulb, Sparkles } from "lucide-react";
import { Bar,BarChart,CartesianGrid,Cell,Legend,Pie,PieChart,ResponsiveContainer,Tooltip,XAxis,YAxis } from "recharts";
import { ChartCard } from "./chart-card";
import { DashboardFilters,type TrendFilters } from "./dashboard-filters";
import { KpiCard } from "./kpi-card";
import { buttonVariants } from "@/components/ui/button";
import type { AIDashboardData,AIDashboardProject } from "@/types/ai-dashboard";

const COLORS=["#6d3fa9","#2e7d5b","#e7a33e","#94a3b8","#a37ad9","#49a87d"];
const initialFilters:TrendFilters={line:"Todos",seedbed:"Todos",trend:"Todos",status:"Todos",gender:"Todos"};
const avg=(items:AIDashboardProject[],key:keyof AIDashboardProject)=>{const done=items.filter((item)=>item.analyzed);return done.length?Math.round(done.reduce((sum,item)=>sum+Number(item[key]||0),0)/done.length*10)/10:0};
const frequency=(values:string[],limit=10)=>{const counts=new Map<string,number>();values.forEach((value)=>{const clean=value.trim();if(clean)counts.set(clean,(counts.get(clean)??0)+1)});return [...counts].sort((a,b)=>b[1]-a[1]).slice(0,limit).map(([name,value])=>({name,value}))};
const dominant=(items:AIDashboardProject[])=>frequency(items.map((item)=>item.trendLevel),1)[0]?.name??"No disponible";
function heat(value:number){const alpha=Math.max(.1,Math.min(.72,value/130));return {backgroundColor:`rgba(46,125,91,${alpha})`,color:value>70?"#ffffff":"#0f172a"}}

export function TendenciasDashboard({data}:{data:AIDashboardData}){
 const [filters,setFilters]=useState(initialFilters);
 const projects=useMemo(()=>data.projects.filter((project)=>(filters.line==="Todos"||project.linea_tematica===filters.line)&&(filters.seedbed==="Todos"||project.semillero===filters.seedbed)&&(filters.trend==="Todos"||project.trendLevel===filters.trend)&&(filters.status==="Todos"||project.estadoAnalisis===filters.status)&&(filters.gender==="Todos"||(filters.gender==="Explícito"?project.explicitGenderFocus:!project.explicitGenderFocus))),[data.projects,filters]);
 const done=projects.filter((project)=>project.analyzed);
 const visual=useMemo(()=>{const groups=new Map<string,AIDashboardProject[]>();projects.forEach((project)=>groups.set(project.linea_tematica,[...(groups.get(project.linea_tematica)??[]),project]));const lines=[...groups].map(([name,items])=>({name,total:items.length,analizados:items.filter((item)=>item.analyzed).length,innovacion:avg(items,"innovation"),pertinencia:avg(items,"pertinence"),impacto:avg(items,"impact"),viabilidad:avg(items,"viability"),claridad:avg(items,"methodologicalClarity"),articulacion:avg(items,"trendArticulation"),genero:items.filter((item)=>item.explicitGenderFocus).length,nivel:dominant(items.filter((item)=>item.analyzed))})).sort((a,b)=>b.total-a.total);return {lines,trend:frequency(projects.map((project)=>project.trendLevel)),gender:[{name:"Con enfoque explícito",value:done.filter((project)=>project.explicitGenderFocus).length},{name:"Sin información explícita",value:done.filter((project)=>project.genderNotReported).length},{name:"No aplica / no reportado",value:projects.filter((project)=>!project.analyzed).length}],women:[{name:"Mujeres involucradas",value:done.filter((project)=>project.womenInvolved).length},{name:"Mujeres en formulación",value:done.filter((project)=>project.womenInFormulation).length},{name:"Mujeres en ejecución",value:done.filter((project)=>project.womenInExecution).length},{name:"No reportado explícitamente",value:done.filter((project)=>project.genderNotReported).length}],keywords:frequency(done.flatMap((project)=>project.keywords)),risks:frequency(done.flatMap((project)=>project.risks)),opportunities:frequency(done.flatMap((project)=>project.opportunities))};},[projects,done]);
 const barTooltip={contentStyle:{borderRadius:12,border:"1px solid #e2e8f0",boxShadow:"0 10px 30px rgba(15,23,42,.10)"}};
 if(data.projects.length===0)return <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center"><p className="font-bold text-slate-900">No hay análisis IA disponibles. Ejecute primero el análisis masivo de proyectos.</p><a className={`${buttonVariants()} mt-5`} href="/admin/tendencias">Analizar proyectos pendientes</a></div>;
 return <div className="space-y-6"><DashboardFilters value={filters} onChange={setFilters} options={data.filters}/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><KpiCard label="Proyectos registrados" value={projects.length} detail="Según filtros activos" icon={BarChart3}/><KpiCard label="Proyectos analizados" value={done.length} detail={`${projects.length-done.length} pendientes`} icon={CheckCircle2} tone="green"/><KpiCard label="Promedio innovación" value={avg(projects,"innovation")} detail="Escala de 0 a 100" icon={Sparkles}/><KpiCard label="Promedio pertinencia" value={avg(projects,"pertinence")} detail="Escala de 0 a 100" icon={Gauge} tone="green"/><KpiCard label="Promedio impacto" value={avg(projects,"impact")} detail="Escala de 0 a 100" icon={Leaf} tone="green"/><KpiCard label="Promedio viabilidad" value={avg(projects,"viability")} detail="Escala de 0 a 100" icon={Lightbulb} tone="orange"/><KpiCard label="Pendientes" value={projects.length-done.length} detail="Pendientes o con error" icon={Clock3} tone="orange"/><KpiCard label="Enfoque de género" value={done.filter((project)=>project.explicitGenderFocus).length} detail="Reportado explícitamente" icon={CheckCircle2} tone="purple"/></div>
 <div className="grid gap-6 xl:grid-cols-2"><ChartCard title="Proyectos por línea temática" description="Comparación entre proyectos registrados y analizados."><div className="h-80"><ResponsiveContainer width="100%" height="100%"><BarChart data={visual.lines} margin={{bottom:48}}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name" angle={-25} textAnchor="end" height={70} interval={0} fontSize={10}/><YAxis allowDecimals={false}/><Tooltip {...barTooltip}/><Legend/><Bar dataKey="total" name="Total" fill="#a37ad9" radius={[7,7,0,0]}/><Bar dataKey="analizados" name="Analizados" fill="#2e7d5b" radius={[7,7,0,0]}/></BarChart></ResponsiveContainer></div></ChartCard><ChartCard title="Promedio de indicadores IA por línea temática" description="Seis dimensiones comparadas en escala de 0 a 100."><div className="h-80"><ResponsiveContainer width="100%" height="100%"><BarChart data={visual.lines}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name" fontSize={10}/><YAxis domain={[0,100]}/><Tooltip {...barTooltip}/><Legend/><Bar dataKey="innovacion" name="Innovación" fill="#6d3fa9"/><Bar dataKey="pertinencia" name="Pertinencia" fill="#2e7d5b"/><Bar dataKey="impacto" name="Impacto" fill="#e7a33e"/><Bar dataKey="viabilidad" name="Viabilidad" fill="#49a87d"/><Bar dataKey="claridad" name="Claridad" fill="#a37ad9"/><Bar dataKey="articulacion" name="Articulación" fill="#64748b"/></BarChart></ResponsiveContainer></div></ChartCard>
 <ChartCard title="Distribución por nivel de tendencia"><div className="h-72"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={visual.trend} dataKey="value" nameKey="name" innerRadius={58} outerRadius={96} paddingAngle={2}>{visual.trend.map((item,index)=><Cell key={item.name} fill={COLORS[index%COLORS.length]}/>)}</Pie><Tooltip {...barTooltip}/><Legend/></PieChart></ResponsiveContainer></div></ChartCard><ChartCard title="Enfoque de género reportado explícitamente"><div className="h-72"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={visual.gender} dataKey="value" nameKey="name" innerRadius={58} outerRadius={96}>{visual.gender.map((item,index)=><Cell key={item.name} fill={COLORS[index%COLORS.length]}/>)}</Pie><Tooltip {...barTooltip}/><Legend/></PieChart></ResponsiveContainer></div></ChartCard>
 <ChartCard title="Participación de mujeres reportada explícitamente"><HorizontalChart data={visual.women}/></ChartCard><ChartCard title="Palabras clave más frecuentes"><HorizontalChart data={visual.keywords}/></ChartCard><ChartCard title="Riesgos frecuentes identificados"><HorizontalChart data={visual.risks} color="#e7a33e"/></ChartCard><ChartCard title="Oportunidades frecuentes identificadas"><HorizontalChart data={visual.opportunities} color="#2e7d5b"/></ChartCard></div>
 <ChartCard title="Matriz de desempeño por línea temática" description="La intensidad de color representa el valor del indicador; el texto conserva contraste alto."><div className="overflow-x-auto"><table className="w-full min-w-[760px] border-separate border-spacing-1 text-sm"><thead><tr>{["Línea temática","Innovación","Pertinencia","Impacto","Viabilidad","Enfoque de género explícito"].map((label)=><th key={label} className="px-3 py-2 text-left text-xs font-bold text-slate-600">{label}</th>)}</tr></thead><tbody>{visual.lines.map((line)=><tr key={line.name}><td className="rounded-lg bg-slate-100 px-3 py-3 font-bold text-slate-950">{line.name}</td>{[line.innovacion,line.pertinencia,line.impacto,line.viabilidad].map((value,index)=><td key={index} className="rounded-lg px-3 py-3 text-center font-extrabold" style={heat(value)}>{value}</td>)}<td className="rounded-lg bg-violet-100 px-3 py-3 text-center font-extrabold text-violet-950">{line.genero} / {line.analizados}</td></tr>)}</tbody></table></div></ChartCard>
 <ChartCard title="Resumen por línea temática"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead className="border-b border-slate-200 bg-slate-50 text-left text-xs uppercase text-slate-600"><tr>{["Línea","Total","Analizados","Innovación","Pertinencia","Impacto","Viabilidad","Tendencia"].map((label)=><th key={label} className="px-3 py-3">{label}</th>)}</tr></thead><tbody>{visual.lines.map((line)=><tr key={line.name} className="border-b border-slate-100"><td className="px-3 py-3 font-bold text-slate-950">{line.name}</td><td className="px-3 py-3">{line.total}</td><td className="px-3 py-3">{line.analizados}</td><td className="px-3 py-3">{line.innovacion}</td><td className="px-3 py-3">{line.pertinencia}</td><td className="px-3 py-3">{line.impacto}</td><td className="px-3 py-3">{line.viabilidad}</td><td className="px-3 py-3">{line.nivel}</td></tr>)}</tbody></table></div></ChartCard>
 <div className="flex justify-end"><a className={buttonVariants()} href="/api/admin/ai/dashboard/report/pdf"><Download/>Descargar reporte PDF</a></div></div>;
}
function HorizontalChart({data,color="#6d3fa9"}:{data:{name:string;value:number}[];color?:string}){if(!data.length)return <p className="flex h-64 items-center justify-center text-sm text-slate-500">Sin datos para los filtros seleccionados.</p>;return <div className="h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={data} layout="vertical" margin={{left:24,right:24}}><CartesianGrid strokeDasharray="3 3" horizontal={false}/><XAxis type="number" allowDecimals={false}/><YAxis dataKey="name" type="category" width={145} fontSize={10}/><Tooltip contentStyle={{borderRadius:12,border:"1px solid #e2e8f0"}}/><Bar dataKey="value" name="Proyectos" fill={color} radius={[0,7,7,0]}/></BarChart></ResponsiveContainer></div>}
