import type {
  AIAnalysis,
  Assignment,
  CertificateRecord,
  EvaluationCriterion,
  EventLogistics,
  Evaluator,
  HumanEvaluation,
  HumanVsAIComparison,
  LogisticsSummary,
  Project,
  TrendByArea,
} from "@/types";

export const proyectosMock: Project[] = [
  {
    codigo: "CAM-2026-001",
    fecha_registro: "2026-03-05T08:30:00-05:00",
    titulo: "Riego inteligente para huertas formativas",
    resumen:
      "Sistema de bajo costo para monitorear humedad del suelo y optimizar riego en unidades productivas de formación.",
    linea_tematica: "Agrícola",
    area_conocimiento: "Agrícola",
    linea_investigacion: "Agrícola",
    modalidad_participacion: "Proyecto en ejecución",
    semillero: "AgroinvLab",
    categoria_presentacion: "Prototipo",
    institucion: "Centro Agroempresarial y Minero",
    municipio: "Pitalito",
    participantes: [
      { nombre: "Laura Medina", documento: "1001001001" },
      { nombre: "Carlos Rojas", documento: "1001001002" },
      { nombre: "Diana Perdomo", documento: "1001001003" },
    ],
    integrantes: ["Laura Medina", "Carlos Rojas", "Diana Perdomo"],
    instructor_nombre: "Martha Gómez",
    instructor_documento: "52000111",
    instructor_correo: "martha.gomez@example.com",
    instructor_celular: "3001112233",
    estado: "Asignado",
    archivo_nombre: "riego-inteligente.pdf",
    archivo_storage_path: "mock-storage-riego",
    archivo_url: "#",
    evaluadores_asignados: 2,
    requiere_certificado: true,
  },
  {
    codigo: "CAM-2026-002",
    fecha_registro: "2026-03-06T09:20:00-05:00",
    titulo: "Clasificador de residuos con visión artificial",
    resumen:
      "Prototipo educativo que identifica residuos aprovechables y promueve hábitos de separación en ambientes de aprendizaje.",
    linea_tematica: "Tecnología e innovación",
    area_conocimiento: "Tecnología e innovación",
    linea_investigacion: "Tecnología e innovación",
    modalidad_participacion: "Proyecto terminado",
    semillero: "Tecnobioma",
    categoria_presentacion: "Ponencia",
    institucion: "Centro Agroempresarial y Minero",
    municipio: "Neiva",
    participantes: [
      { nombre: "Andrés Cárdenas", documento: "1002002001" },
      { nombre: "Paula Salazar", documento: "1002002002" },
    ],
    integrantes: ["Andrés Cárdenas", "Paula Salazar"],
    instructor_nombre: "Jorge Ramírez",
    instructor_documento: "79000222",
    instructor_correo: "jorge.ramirez@example.com",
    instructor_celular: "3002223344",
    estado: "Evaluado",
    archivo_nombre: "clasificador-residuos.pdf",
    archivo_storage_path: "mock-storage-residuos",
    archivo_url: "#",
    evaluadores_asignados: 2,
    requiere_certificado: true,
  },
  {
    codigo: "CAM-2026-003",
    fecha_registro: "2026-03-07T10:10:00-05:00",
    titulo: "Biofertilizante a partir de residuos orgánicos",
    resumen:
      "Aprovechamiento de residuos agroindustriales para formular un bioinsumo aplicable a cultivos locales.",
    linea_tematica: "Ambiental",
    area_conocimiento: "Ambiental",
    linea_investigacion: "Ambiental",
    modalidad_participacion: "Proyecto en ejecución",
    semillero: "Ambiental",
    categoria_presentacion: "Poster",
    institucion: "Centro Agroempresarial y Minero",
    municipio: "La Plata",
    participantes: [
      { nombre: "Natalia Torres", documento: "1003003001" },
      { nombre: "Miguel Andrade", documento: "1003003002" },
    ],
    integrantes: ["Natalia Torres", "Miguel Andrade"],
    instructor_nombre: "Sandra Vargas",
    instructor_documento: "63000333",
    instructor_correo: "sandra.vargas@example.com",
    instructor_celular: "3003334455",
    estado: "En evaluación",
    archivo_nombre: "biofertilizante.pdf",
    archivo_storage_path: "mock-storage-bio",
    archivo_url: "#",
    evaluadores_asignados: 1,
    requiere_certificado: true,
  },
  {
    codigo: "CAM-2026-004",
    fecha_registro: "2026-03-08T11:00:00-05:00",
    titulo: "Modelo administrativo para ferias campesinas",
    resumen:
      "Herramienta de organización operativa para mejorar turnos, inventarios y seguimiento comercial en ferias locales.",
    linea_tematica: "Administrativa",
    area_conocimiento: "Administrativa",
    linea_investigacion: "Administrativa",
    modalidad_participacion: "Propuesta de investigación",
    semillero: "Administrativo Naranjos",
    categoria_presentacion: "Oral",
    institucion: "Centro Agroempresarial y Minero",
    municipio: "Garzón",
    participantes: [{ nombre: "Camila Duarte", documento: "1004004001" }],
    integrantes: ["Camila Duarte"],
    instructor_nombre: "Hernán Osorio",
    instructor_documento: "80000444",
    instructor_correo: "hernan.osorio@example.com",
    instructor_celular: "3004445566",
    estado: "Registrado",
    archivo_nombre: "ferias-campesinas.pdf",
    archivo_storage_path: "mock-storage-ferias",
    archivo_url: "#",
    evaluadores_asignados: 0,
    requiere_certificado: true,
  },
  {
    codigo: "CAM-2026-005",
    fecha_registro: "2026-03-09T14:15:00-05:00",
    titulo: "Monitoreo apícola para colmenas escuela",
    resumen:
      "Dispositivo de seguimiento de temperatura y actividad para fortalecer prácticas apícolas seguras.",
    linea_tematica: "Apícola",
    area_conocimiento: "Apícola",
    linea_investigacion: "Apícola",
    modalidad_participacion: "Proyecto en ejecución",
    semillero: "Aspillanos",
    categoria_presentacion: "Prototipo",
    institucion: "Centro Agroempresarial y Minero",
    municipio: "Campoalegre",
    participantes: [
      { nombre: "Sofía Molina", documento: "1005005001" },
      { nombre: "Iván Pardo", documento: "1005005002" },
    ],
    integrantes: ["Sofía Molina", "Iván Pardo"],
    instructor_nombre: "Claudia Marín",
    instructor_documento: "65000555",
    instructor_correo: "claudia.marin@example.com",
    instructor_celular: "3005556677",
    estado: "Asignado",
    archivo_nombre: "monitoreo-apicola.pdf",
    archivo_storage_path: "mock-storage-apicola",
    archivo_url: "#",
    evaluadores_asignados: 1,
    requiere_certificado: true,
  },
  {
    codigo: "CAM-2026-006",
    fecha_registro: "2026-03-09T15:00:00-05:00",
    titulo: "Sensorización de germinación en viveros",
    resumen:
      "Seguimiento de humedad, luminosidad y temperatura para mejorar la germinación en viveros de aprendizaje.",
    linea_tematica: "Agrícola",
    area_conocimiento: "Agrícola",
    linea_investigacion: "Agrícola",
    modalidad_participacion: "Proyecto en ejecución",
    semillero: "Agrícola",
    categoria_presentacion: "Poster",
    institucion: "Centro Agroempresarial y Minero",
    municipio: "Rivera",
    participantes: [{ nombre: "Julián Patiño", documento: "1006006001" }],
    integrantes: ["Julián Patiño"],
    instructor_nombre: "Martha Gómez",
    instructor_documento: "52000111",
    instructor_correo: "martha.gomez@example.com",
    instructor_celular: "3001112233",
    estado: "Asignado",
    archivo_nombre: "germinacion-viveros.pdf",
    archivo_storage_path: "mock-storage-germinacion",
    archivo_url: "#",
    evaluadores_asignados: 1,
    requiere_certificado: true,
  },
  {
    codigo: "CAM-2026-007",
    fecha_registro: "2026-03-09T16:00:00-05:00",
    titulo: "Bitácora digital de cultivo de café",
    resumen:
      "Aplicación de seguimiento para labores, insumos y observaciones técnicas en parcelas demostrativas de café.",
    linea_tematica: "Agrícola",
    area_conocimiento: "Agrícola",
    linea_investigacion: "Agrícola",
    modalidad_participacion: "Propuesta de investigación",
    semillero: "Cienciatec",
    categoria_presentacion: "Oral",
    institucion: "Centro Agroempresarial y Minero",
    municipio: "Timaná",
    participantes: [{ nombre: "Mariana Tovar", documento: "1007007001" }],
    integrantes: ["Mariana Tovar"],
    instructor_nombre: "Martha Gómez",
    instructor_documento: "52000111",
    instructor_correo: "martha.gomez@example.com",
    instructor_celular: "3001112233",
    estado: "Asignado",
    archivo_nombre: "bitacora-cafe.pdf",
    archivo_storage_path: "mock-storage-cafe",
    archivo_url: "#",
    evaluadores_asignados: 1,
    requiere_certificado: true,
  },
];

export const evaluadoresMock: Evaluator[] = [
  {
    evaluador_id: "EVAL-001",
    fecha_registro: "2026-03-10T08:00:00-05:00",
    nombre: "Adriana Salcedo",
    correo: "adriana.salcedo@example.com",
    celular: "3101112233",
    documento: "52001001",
    entidad: "SENA",
    area_conocimiento: "Agrícola",
    disponibilidad: "Mañana",
    proyectos_asignados: 3,
    max_proyectos: 3,
    estado: "Completo",
    requiere_certificado: true,
  },
  {
    evaluador_id: "EVAL-002",
    fecha_registro: "2026-03-10T08:30:00-05:00",
    nombre: "Felipe Castaño",
    correo: "felipe.castano@example.com",
    celular: "3102223344",
    documento: "79002002",
    entidad: "Universidad Surcolombiana",
    area_conocimiento: "Tecnología e innovación",
    disponibilidad: "Tarde",
    proyectos_asignados: 1,
    max_proyectos: 3,
    estado: "Disponible",
    requiere_certificado: true,
  },
  {
    evaluador_id: "EVAL-003",
    fecha_registro: "2026-03-10T09:00:00-05:00",
    nombre: "Liliana Fajardo",
    correo: "liliana.fajardo@example.com",
    celular: "3103334455",
    documento: "63003003",
    entidad: "CAM",
    area_conocimiento: "Ambiental",
    disponibilidad: "Jornada completa",
    proyectos_asignados: 1,
    max_proyectos: 3,
    estado: "Disponible",
    requiere_certificado: true,
  },
  {
    evaluador_id: "EVAL-004",
    fecha_registro: "2026-03-10T09:30:00-05:00",
    nombre: "Roberto Anaya",
    correo: "roberto.anaya@example.com",
    celular: "3104445566",
    documento: "80004004",
    entidad: "Sector productivo",
    area_conocimiento: "Apícola",
    disponibilidad: "Mañana",
    proyectos_asignados: 1,
    max_proyectos: 3,
    estado: "Disponible",
    requiere_certificado: true,
  },
  {
    evaluador_id: "EVAL-005",
    fecha_registro: "2026-03-10T10:00:00-05:00",
    nombre: "Diana Murillo",
    correo: "diana.murillo@example.com",
    celular: "3105556677",
    documento: "67005005",
    entidad: "SENA",
    area_conocimiento: "Administrativa",
    disponibilidad: "Tarde",
    proyectos_asignados: 0,
    max_proyectos: 3,
    estado: "Disponible",
    requiere_certificado: true,
  },
  {
    evaluador_id: "EVAL-006",
    fecha_registro: "2026-03-10T10:30:00-05:00",
    nombre: "Óscar Rivera",
    correo: "oscar.rivera@example.com",
    celular: "3106667788",
    documento: "72006006",
    entidad: "Sector productivo",
    area_conocimiento: "Agrícola",
    disponibilidad: "Jornada completa",
    proyectos_asignados: 1,
    max_proyectos: 3,
    estado: "Disponible",
    requiere_certificado: true,
  },
  {
    evaluador_id: "EVAL-007",
    fecha_registro: "2026-03-10T11:00:00-05:00",
    nombre: "Marcela Prieto",
    correo: "marcela.prieto@example.com",
    celular: "3107778899",
    documento: "43007007",
    entidad: "Tecnoparque",
    area_conocimiento: "Tecnología e innovación",
    disponibilidad: "Mañana",
    proyectos_asignados: 1,
    max_proyectos: 3,
    estado: "Disponible",
    requiere_certificado: true,
  },
];

export const asignacionesMock: Assignment[] = [
  {
    asignacion_id: "ASIG-001",
    codigo_proyecto: "CAM-2026-001",
    titulo_proyecto: "Riego inteligente para huertas formativas",
    evaluador_id: "EVAL-001",
    evaluador_nombre: "Adriana Salcedo",
    area_conocimiento: "Agrícola",
    token: "tok_riego_001",
    fecha_asignacion: "2026-03-12T08:00:00-05:00",
    estado: "En proceso",
    archivo_abierto: true,
    fecha_apertura_archivo: "2026-03-12T09:00:00-05:00",
  },
  {
    asignacion_id: "ASIG-002",
    codigo_proyecto: "CAM-2026-001",
    titulo_proyecto: "Riego inteligente para huertas formativas",
    evaluador_id: "EVAL-006",
    evaluador_nombre: "Óscar Rivera",
    area_conocimiento: "Agrícola",
    token: "tok_riego_002",
    fecha_asignacion: "2026-03-12T08:10:00-05:00",
    estado: "Pendiente",
    archivo_abierto: false,
  },
  {
    asignacion_id: "ASIG-003",
    codigo_proyecto: "CAM-2026-002",
    titulo_proyecto: "Clasificador de residuos con visión artificial",
    evaluador_id: "EVAL-002",
    evaluador_nombre: "Felipe Castaño",
    area_conocimiento: "Tecnología e innovación",
    token: "tok_residuos_001",
    fecha_asignacion: "2026-03-12T08:20:00-05:00",
    estado: "Completada",
    archivo_abierto: true,
    fecha_apertura_archivo: "2026-03-12T10:15:00-05:00",
  },
  {
    asignacion_id: "ASIG-004",
    codigo_proyecto: "CAM-2026-002",
    titulo_proyecto: "Clasificador de residuos con visión artificial",
    evaluador_id: "EVAL-007",
    evaluador_nombre: "Marcela Prieto",
    area_conocimiento: "Tecnología e innovación",
    token: "tok_residuos_002",
    fecha_asignacion: "2026-03-12T08:30:00-05:00",
    estado: "En proceso",
    archivo_abierto: true,
    fecha_apertura_archivo: "2026-03-12T11:00:00-05:00",
  },
  {
    asignacion_id: "ASIG-005",
    codigo_proyecto: "CAM-2026-003",
    titulo_proyecto: "Biofertilizante a partir de residuos orgánicos",
    evaluador_id: "EVAL-003",
    evaluador_nombre: "Liliana Fajardo",
    area_conocimiento: "Ambiental",
    token: "tok_bio_001",
    fecha_asignacion: "2026-03-12T08:40:00-05:00",
    estado: "Pendiente",
    archivo_abierto: false,
  },
  {
    asignacion_id: "ASIG-006",
    codigo_proyecto: "CAM-2026-005",
    titulo_proyecto: "Monitoreo apícola para colmenas escuela",
    evaluador_id: "EVAL-004",
    evaluador_nombre: "Roberto Anaya",
    area_conocimiento: "Apícola",
    token: "tok_apicola_001",
    fecha_asignacion: "2026-03-12T08:50:00-05:00",
    estado: "Pendiente",
    archivo_abierto: false,
  },
  {
    asignacion_id: "ASIG-007",
    codigo_proyecto: "CAM-2026-006",
    titulo_proyecto: "Sensorización de germinación en viveros",
    evaluador_id: "EVAL-001",
    evaluador_nombre: "Adriana Salcedo",
    area_conocimiento: "Agrícola",
    token: "tok_germinacion_001",
    fecha_asignacion: "2026-03-12T09:00:00-05:00",
    estado: "Pendiente",
    archivo_abierto: false,
  },
  {
    asignacion_id: "ASIG-008",
    codigo_proyecto: "CAM-2026-007",
    titulo_proyecto: "Bitácora digital de cultivo de café",
    evaluador_id: "EVAL-001",
    evaluador_nombre: "Adriana Salcedo",
    area_conocimiento: "Agrícola",
    token: "tok_cafe_001",
    fecha_asignacion: "2026-03-12T09:10:00-05:00",
    estado: "Pendiente",
    archivo_abierto: false,
  },
];

export const criteriosEvaluacionMock: EvaluationCriterion[] = [
  {
    criterio_id: "CRIT-001",
    nombre: "Pertinencia",
    descripcion: "Relación con necesidades del territorio y del evento.",
    puntaje_maximo: 20,
  },
  {
    criterio_id: "CRIT-002",
    nombre: "Innovación",
    descripcion: "Novedad, creatividad o mejora frente al contexto.",
    puntaje_maximo: 20,
  },
  {
    criterio_id: "CRIT-003",
    nombre: "Metodología",
    descripcion: "Claridad del problema, objetivos, actividades y validación.",
    puntaje_maximo: 20,
  },
  {
    criterio_id: "CRIT-004",
    nombre: "Impacto",
    descripcion: "Beneficios esperados, sostenibilidad y aplicabilidad.",
    puntaje_maximo: 20,
  },
  {
    criterio_id: "CRIT-005",
    nombre: "Comunicación",
    descripcion: "Calidad documental y claridad de presentación.",
    puntaje_maximo: 20,
  },
];

export const evaluacionesMock: HumanEvaluation[] = [
  {
    evaluacion_id: "EVALH-001",
    asignacion_id: "ASIG-003",
    proyecto_id: "CAM-2026-002",
    evaluador_id: "EVAL-002",
    estado: "Completada",
    puntaje_pertinencia: 18,
    puntaje_innovacion: 18,
    puntaje_metodologia: 17,
    puntaje_impacto: 18,
    puntaje_comunicacion: 17,
    puntaje_total: 88,
    observaciones: "Proyecto claro y pertinente para procesos educativos ambientales.",
    fortalezas: "Claridad metodológica y potencial de sensibilización.",
    oportunidades: "Ampliar pruebas con más tipos de residuos.",
    recomendacion_final: "Destacado",
    concepto_evaluador:
      "Proyecto pertinente con buen nivel de prototipo y aplicación pedagógica.",
    fecha_envio: "2026-03-14T15:45:00-05:00",
  },
  {
    evaluacion_id: "EVALH-002",
    asignacion_id: "ASIG-006",
    proyecto_id: "CAM-2026-005",
    evaluador_id: "EVAL-004",
    estado: "Completada",
    puntaje_pertinencia: 16,
    puntaje_innovacion: 17,
    puntaje_metodologia: 15,
    puntaje_impacto: 16,
    puntaje_comunicacion: 15,
    puntaje_total: 79,
    observaciones: "La propuesta es aplicable a prácticas apícolas formativas.",
    fortalezas: "Buen enfoque de monitoreo y seguridad para colmenas escuela.",
    oportunidades: "Profundizar en calibración de sensores y mantenimiento.",
    recomendacion_final: "Aprobar",
    concepto_evaluador:
      "Proyecto viable con aportes técnicos claros para formación apícola.",
    fecha_envio: "2026-03-15T11:20:00-05:00",
  },
];

export const analisisIAMock: AIAnalysis[] = [
  {
    analisis_id: "IA-001",
    proyecto_id: "CAM-2026-001",
    archivo_storage_path: "mock-storage-riego",
    estado: "Pendiente",
    resumen_ia: "",
    tendencias_identificadas: [],
    puntaje_sugerido_ia: null,
    nivel_tendencia_ia: "No disponible",
    concepto_ia: "Análisis IA pendiente.",
    alertas_calidad: [],
  },
  {
    analisis_id: "IA-002",
    proyecto_id: "CAM-2026-002",
    archivo_storage_path: "mock-storage-residuos",
    estado: "Completado",
    resumen_ia:
      "El documento describe un prototipo de visión artificial para clasificar residuos y apoyar procesos educativos ambientales.",
    tendencias_identificadas: [
      "IA aplicada",
      "Economía circular",
      "Educación ambiental",
    ],
    puntaje_sugerido_ia: 85,
    nivel_tendencia_ia: "Alto",
    concepto_ia:
      "Iniciativa alineada con sostenibilidad y apropiación tecnológica; requiere mayor evidencia de validación.",
    alertas_calidad: ["Falta detalle sobre tamaño de muestra en pruebas."],
    fecha_analisis: "2026-03-14T16:10:00-05:00",
  },
  {
    analisis_id: "IA-003",
    proyecto_id: "CAM-2026-005",
    archivo_storage_path: "mock-storage-apicola",
    estado: "Completado",
    resumen_ia:
      "El archivo plantea monitoreo de variables críticas en colmenas escuela para mejorar prácticas de formación apícola.",
    tendencias_identificadas: [
      "Agrotecnología",
      "Sensórica",
      "Buenas prácticas apícolas",
    ],
    puntaje_sugerido_ia: 81,
    nivel_tendencia_ia: "Medio",
    concepto_ia:
      "La tendencia técnica es relevante; conviene reforzar validación, costos y protocolo de operación.",
    alertas_calidad: ["El cronograma necesita mayor precisión."],
    fecha_analisis: "2026-03-15T12:00:00-05:00",
  },
  {
    analisis_id: "IA-004",
    proyecto_id: "CAM-2026-003",
    archivo_storage_path: "mock-storage-bio",
    estado: "Procesando",
    resumen_ia: "",
    tendencias_identificadas: [],
    puntaje_sugerido_ia: null,
    nivel_tendencia_ia: "No disponible",
    concepto_ia: "Análisis IA en procesamiento.",
    alertas_calidad: [],
  },
];

export const logisticaMock: EventLogistics = {
  fecha_evento: "2026-05-22",
  sede: "Centro Agroempresarial y Minero",
  aulas_requeridas: 6,
  mesas_evaluacion: 12,
  franjas: [
    {
      nombre: "Apertura y posters",
      hora_inicio: "08:00",
      hora_fin: "10:00",
      proyectos_programados: 12,
    },
    {
      nombre: "Prototipos y ponencias",
      hora_inicio: "10:30",
      hora_fin: "12:30",
      proyectos_programados: 18,
    },
    {
      nombre: "Cierre y certificados",
      hora_inicio: "14:00",
      hora_fin: "16:00",
      proyectos_programados: 5,
    },
  ],
};

export const certificadosMock: CertificateRecord[] = [
  {
    certificado_id: "CERT-001",
    tipo: "Participante",
    nombre: "Laura Medina",
    documento: "1001001001",
    codigo_proyecto: "CAM-2026-001",
    rol: "Participante",
    fecha_evento: "2026-05-22",
    estado: "Pendiente",
  },
  {
    certificado_id: "CERT-002",
    tipo: "Instructor",
    nombre: "Martha Gómez",
    documento: "52000111",
    codigo_proyecto: "CAM-2026-001",
    rol: "Instructor",
    fecha_evento: "2026-05-22",
    estado: "Pendiente",
  },
  {
    certificado_id: "CERT-003",
    tipo: "Evaluador",
    nombre: "Felipe Castaño",
    documento: "79002002",
    codigo_proyecto: "CAM-2026-002",
    rol: "Evaluador",
    fecha_evento: "2026-05-22",
    estado: "Generado",
    archivo_certificado_url: "#",
  },
  {
    certificado_id: "CERT-004",
    tipo: "Participante",
    nombre: "Sofía Molina",
    documento: "1005005001",
    codigo_proyecto: "CAM-2026-005",
    rol: "Participante",
    fecha_evento: "2026-05-22",
    estado: "Enviado",
    archivo_certificado_url: "#",
  },
];

export const tendenciasPorAreaMock: TrendByArea[] = [
  { area: "Agrícola", proyectos: 3, puntajePromedio: 82 },
  { area: "Ambiental", proyectos: 1, puntajePromedio: 79 },
  { area: "Tecnología e innovación", proyectos: 1, puntajePromedio: 86 },
  { area: "Pecuaria", proyectos: 0, puntajePromedio: 0 },
  { area: "Apícola", proyectos: 1, puntajePromedio: 80 },
  { area: "Administrativa", proyectos: 1, puntajePromedio: 78 },
  { area: "Agroindustria", proyectos: 0, puntajePromedio: 0 },
];

export const comparacionesHumanoIaMock: HumanVsAIComparison[] = evaluacionesMock.map(
  (evaluacion) => {
    const analisis = analisisIAMock.find(
      (item) => item.proyecto_id === evaluacion.proyecto_id,
    );
    const puntajeIA =
      analisis?.estado === "Completado" ? analisis.puntaje_sugerido_ia : null;

    return {
      codigo_proyecto: evaluacion.proyecto_id,
      puntaje_humano: evaluacion.puntaje_total,
      puntaje_ia: puntajeIA,
      diferencia:
        puntajeIA === null ? null : Math.abs(evaluacion.puntaje_total - puntajeIA),
      concepto_evaluador: evaluacion.concepto_evaluador,
      concepto_ia: analisis?.concepto_ia,
    };
  },
);

export const asignacionesPendientesMock = asignacionesMock.filter(
  (item) => item.estado !== "Completada",
).length;

export const resumenLogisticaMock: LogisticsSummary = {
  proyectos: proyectosMock.length,
  evaluadores: evaluadoresMock.length,
  asignaciones: asignacionesMock.length,
  evaluaciones: evaluacionesMock.length,
  certificadosPendientes: certificadosMock.filter(
    (item) => item.estado === "Pendiente",
  ).length,
  proyectosSinEvaluador: proyectosMock.filter(
    (item) => item.evaluadores_asignados === 0,
  ).length,
  proyectosConUnEvaluador: proyectosMock.filter(
    (item) => item.evaluadores_asignados === 1,
  ).length,
  proyectosConDosEvaluadores: proyectosMock.filter(
    (item) => item.evaluadores_asignados === 2,
  ).length,
};

export function getProyectoByCodigo(codigo: string) {
  return proyectosMock.find((proyecto) => proyecto.codigo === codigo);
}

export function getAsignacionesByProyecto(codigo: string) {
  return asignacionesMock.filter((item) => item.codigo_proyecto === codigo);
}

export function getEvaluacionesByProyecto(codigo: string) {
  return evaluacionesMock.filter((item) => item.proyecto_id === codigo);
}

export function getAnalisisIAByProyecto(codigo: string) {
  return analisisIAMock.find((item) => item.proyecto_id === codigo);
}

export function getEvaluacionByToken(token: string) {
  const asignacion = asignacionesMock.find((item) => item.token === token);
  const codigoProyecto = asignacion?.codigo_proyecto;
  const proyecto = codigoProyecto
    ? getProyectoByCodigo(codigoProyecto)
    : undefined;
  const analisis = proyecto ? getAnalisisIAByProyecto(proyecto.codigo) : undefined;

  return { asignacion, proyecto, analisis };
}
