import { createSupabaseServerClient } from "@/lib/supabase/server";
import type { AIDashboardChartItem, AIDashboardData, AIDashboardLine, AIDashboardProject } from "@/types/ai-dashboard";

type Row = Record<string, unknown>;
const num = (value: unknown) => Number(value) || 0;
const arr = (value: unknown) => Array.isArray(value) ? value.filter((item): item is string => typeof item === "string" && Boolean(item.trim())) : [];
const reported = (value: unknown) => { const text = String(value ?? "").trim().toLowerCase(); return Boolean(text && text !== "pendiente" && text !== "no reportado explícitamente" && text !== "no reportado explicitamente" && !text.startsWith("no se evidencia")); };
const analysisTime = (row: Row) => Date.parse(String(row.fecha_analisis || row.created_at || "")) || 0;
const average = (rows: Row[], key: string) => rows.length ? Math.round(rows.reduce((sum,row)=>sum+num(row[key]),0)/rows.length*10)/10 : 0;
function counted(values:string[],limit=10):AIDashboardChartItem[]{const counts=new Map<string,number>();values.forEach((value)=>{const clean=value.trim();if(clean)counts.set(clean,(counts.get(clean)??0)+1)});return [...counts].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])).slice(0,limit).map(([name,value])=>({name,value}));}
const top=(values:string[],limit=5)=>counted(values,limit).map((item)=>item.name);
const dominant=(rows:Row[])=>top(rows.map((row)=>String(row.nivel_tendencia_ia??"")).filter(Boolean),1)[0]??"No disponible";

export async function getAIDashboardData():Promise<AIDashboardData>{
 const db=createSupabaseServerClient();
 const [{data:projects,error:projectError},{data:analyses,error:analysisError}]=await Promise.all([
  db.from("proyectos").select("id,linea_tematica,linea_tematica_otro,semillero,semillero_otro,estado_analisis_ia"),
  db.from("analisis_ia").select("*"),
 ]);
 if(projectError)throw projectError;if(analysisError)throw analysisError;
 const latest=new Map<string,Row>();
 for(const row of ((analyses??[]) as Row[]).sort((a,b)=>analysisTime(b)-analysisTime(a))){const id=String(row.proyecto_id??"");if(id&&!latest.has(id))latest.set(id,row);}
 const projectRows=(projects??[]) as Row[];
 const dashboardProjects:AIDashboardProject[]=projectRows.map((project)=>{
  const analysis=latest.get(String(project.id));const analyzed=Boolean(analysis&&(analysis.estado_analisis==="Completado"||analysis.estado==="Completado"));
  const line=String(project.linea_tematica==="Otra"?project.linea_tematica_otro||"Otra":project.linea_tematica||"Sin línea");
  const semillero=String(project.semillero==="Otro"?project.semillero_otro||"Otro":project.semillero||"Sin semillero");
  return {id:String(project.id),linea_tematica:line,semillero,estadoAnalisis:String(project.estado_analisis_ia||"Pendiente"),analyzed,trendLevel:analyzed?String(analysis?.nivel_tendencia_ia||"No reportado"):"No reportado",innovation:analyzed?num(analysis?.nivel_innovacion_ia):0,pertinence:analyzed?num(analysis?.nivel_pertinencia_ia):0,impact:analyzed?num(analysis?.nivel_impacto_ia):0,viability:analyzed?num(analysis?.nivel_viabilidad_ia):0,methodologicalClarity:analyzed?num(analysis?.nivel_claridad_metodologica_ia):0,trendArticulation:analyzed?num(analysis?.nivel_articulacion_tendencias_ia):0,explicitGenderFocus:analyzed&&reported(analysis?.enfoque_genero_ia),womenInvolved:analyzed&&reported(analysis?.mujeres_involucradas_ia),womenInFormulation:analyzed&&reported(analysis?.mujeres_en_formulacion_ia),womenInExecution:analyzed&&reported(analysis?.mujeres_en_ejecucion_ia),genderNotReported:analyzed&&!reported(analysis?.evidencia_genero_ia)&&!reported(analysis?.enfoque_genero_ia),keywords:analyzed?arr(analysis?.palabras_clave_ia):[],risks:analyzed?arr(analysis?.riesgos_detectados):[],opportunities:analyzed?arr(analysis?.oportunidades_detectadas):[]};
 });
 const groups=new Map<string,AIDashboardProject[]>();dashboardProjects.forEach((project)=>groups.set(project.linea_tematica,[...(groups.get(project.linea_tematica)??[]),project]));
 const byLine:AIDashboardLine[]=[...groups].map(([line,items])=>{const done=items.filter((item)=>item.analyzed);const rows=done as unknown as Row[];return {linea_tematica:line,totalProjects:items.length,analyzedProjects:done.length,avgInnovation:average(rows,"innovation"),avgPertinence:average(rows,"pertinence"),avgImpact:average(rows,"impact"),avgViability:average(rows,"viability"),dominantTrendLevel:counted(done.map((item)=>item.trendLevel),1)[0]?.name??"No disponible",keywords:top(done.flatMap((item)=>item.keywords)),opportunities:top(done.flatMap((item)=>item.opportunities)),risks:top(done.flatMap((item)=>item.risks)),explicitGenderFocus:done.filter((item)=>item.explicitGenderFocus).length,womenInFormulation:done.filter((item)=>item.womenInFormulation).length,womenInExecution:done.filter((item)=>item.womenInExecution).length,genderNotReported:done.filter((item)=>item.genderNotReported).length};}).sort((a,b)=>b.totalProjects-a.totalProjects||a.linea_tematica.localeCompare(b.linea_tematica));
 const completed=dashboardProjects.filter((project)=>project.analyzed);const completedRows=completed as unknown as Row[];
 const indicatorsByLine=byLine.map((line)=>{const rows=completed.filter((project)=>project.linea_tematica===line.linea_tematica) as unknown as Row[];return {name:line.linea_tematica,value:line.avgInnovation,innovacion:line.avgInnovation,pertinencia:line.avgPertinence,impacto:line.avgImpact,viabilidad:line.avgViability,claridad:average(rows,"methodologicalClarity"),articulacion:average(rows,"trendArticulation")};});
 const charts={projectsByLine:byLine.map((line)=>({name:line.linea_tematica,value:line.totalProjects,analizados:line.analyzedProjects})),indicatorsByLine,trendLevels:counted(dashboardProjects.map((project)=>project.trendLevel)),genderFocus:[{name:"Con enfoque explícito",value:completed.filter((project)=>project.explicitGenderFocus).length},{name:"Sin información explícita",value:completed.filter((project)=>project.genderNotReported).length},{name:"No aplica / no reportado",value:dashboardProjects.filter((project)=>!project.analyzed).length}],womenParticipation:[{name:"Mujeres involucradas",value:completed.filter((project)=>project.womenInvolved).length},{name:"Mujeres en formulación",value:completed.filter((project)=>project.womenInFormulation).length},{name:"Mujeres en ejecución",value:completed.filter((project)=>project.womenInExecution).length},{name:"No reportado explícitamente",value:completed.filter((project)=>project.genderNotReported).length}],topKeywords:counted(completed.flatMap((project)=>project.keywords)),topRisks:counted(completed.flatMap((project)=>project.risks)),topOpportunities:counted(completed.flatMap((project)=>project.opportunities)),heatmapByLine:indicatorsByLine.map((item)=>({...item,genero:byLine.find((line)=>line.linea_tematica===item.name)?.explicitGenderFocus??0}))};
 const last=[...latest.values()].sort((a,b)=>analysisTime(b)-analysisTime(a))[0];const lastBulkAnalysis=last?String(last.fecha_analisis||last.created_at||"")||null:null;
 const summary={totalProjects:dashboardProjects.length,analyzedProjects:completed.length,pendingProjects:dashboardProjects.filter((project)=>!project.analyzed).length,failedProjects:dashboardProjects.filter((project)=>project.estadoAnalisis==="Error").length,thematicLines:groups.size,avgInnovation:average(completedRows,"innovation"),avgPertinence:average(completedRows,"pertinence"),avgImpact:average(completedRows,"impact"),avgViability:average(completedRows,"viability"),explicitGenderFocus:completed.filter((project)=>project.explicitGenderFocus).length,womenInvolved:completed.filter((project)=>project.womenInvolved).length,womenInFormulation:completed.filter((project)=>project.womenInFormulation).length,womenInExecution:completed.filter((project)=>project.womenInExecution).length,genderNotReported:completed.filter((project)=>project.genderNotReported).length,topTrends:top([...latest.values()].flatMap((row)=>arr(row.tendencias_identificadas))),topRisks:top(completed.flatMap((project)=>project.risks)),topOpportunities:top(completed.flatMap((project)=>project.opportunities)),genderGaps:top([...latest.values()].flatMap((row)=>arr(row.brechas_genero_ia))),genderActions:top([...latest.values()].flatMap((row)=>arr(row.acciones_genero_recomendadas_ia))),lastBulkAnalysis};
 const filters={lineas:[...new Set(dashboardProjects.map((project)=>project.linea_tematica))].sort(),semilleros:[...new Set(dashboardProjects.map((project)=>project.semillero))].sort(),nivelesTendencia:[...new Set(dashboardProjects.map((project)=>project.trendLevel))].sort(),estadosAnalisis:[...new Set(dashboardProjects.map((project)=>project.estadoAnalisis))].sort()};
 return {success:true,summary,byLine,charts,filters,projects:dashboardProjects};
}
