import { analyzeProductor } from "./productores-analysis";
import { isOpenRouterRateLimitError } from "./openrouter";
import { normalizeAnalysisForDatabase, validateAnalysisArrays } from "./analysis-normalization";
import type { ProductorIniciativa } from "@/types/productores";
type Db=ReturnType<typeof import("@/lib/supabase/server").createSupabaseServerClient>;
const detail=(e:unknown)=>e instanceof Error?e.message.slice(0,1200):String(e).slice(0,1200);
export async function analyzeAndSaveProductor(db:Db,row:Record<string,unknown>,options:{timeoutMs?:number}={}){
 const id=String(row.id);const code=String(row.codigo_iniciativa||id);const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),options.timeoutMs??60000);await db.from("productores_iniciativas").update({estado_analisis_ia:"Procesando"}).eq("id",id);
 try{const analysis=await analyzeProductor(row as unknown as ProductorIniciativa,controller.signal);const payload=normalizeAnalysisForDatabase({...analysis,estado_analisis:"Completado",mensaje_error:"",fecha_analisis:new Date().toISOString()});validateAnalysisArrays(payload);const {data:existing}=await db.from("analisis_ia_productores").select("id").eq("iniciativa_id",id).maybeSingle();const query=existing?db.from("analisis_ia_productores").update(payload).eq("id",existing.id):db.from("analisis_ia_productores").insert({iniciativa_id:id,...payload});const {error}=await query;if(error)throw error;await db.from("productores_iniciativas").update({estado_analisis_ia:"Completado"}).eq("id",id);return {success:true as const,code};}
 catch(error){if(isOpenRouterRateLimitError(error)){await db.from("productores_iniciativas").update({estado_analisis_ia:"Pendiente"}).eq("id",id);return {success:false as const,paused:true as const,code,error:error.message};}const message=detail(error);await db.from("productores_iniciativas").update({estado_analisis_ia:"Error"}).eq("id",id);const {data:existing}=await db.from("analisis_ia_productores").select("id").eq("iniciativa_id",id).maybeSingle();const failure=normalizeAnalysisForDatabase({estado_analisis:"Error",mensaje_error:message,modelo_ia:process.env.OPENROUTER_MODEL||"openrouter/fallback",fecha_analisis:new Date().toISOString()});if(existing)await db.from("analisis_ia_productores").update(failure).eq("id",existing.id);else await db.from("analisis_ia_productores").insert({iniciativa_id:id,...failure});return {success:false as const,code,error:message};}finally{clearTimeout(timeout);}
}
