import type { ProductoresDashboardData } from "@/types/productores-ai-dashboard";
const W=612,H=792,M=46;const clean=(v:unknown)=>String(v??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[\u2010-\u2015]/g,"-").replace(/[^\x20-\xFF]/g,"");const esc=(v:unknown)=>clean(v).replace(/\\/g,"\\\\").replace(/\(/g,"\\(").replace(/\)/g,"\\)");
function wrap(value:unknown,width=88){const words=clean(value).split(/\s+/);const out:string[]=[];let line="";for(const word of words){if(`${line} ${word}`.trim().length>width){if(line)out.push(line);line=word;}else line=`${line} ${word}`.trim();}if(line)out.push(line);return out.length?out:[""];}
export function buildProductoresDashboardPdf(data:ProductoresDashboardData){const pages:string[][]=[[]];let page=0,y=H-M;const next=()=>{pages.push([]);page++;y=H-M;};const line=(value:unknown,size=9,bold=false)=>{for(const row of wrap(value,bold?76:90)){if(y<M+28)next();pages[page].push(`BT /${bold?"F2":"F1"} ${size} Tf 0 0 0 rg 1 0 0 1 ${M} ${y} Tm (${esc(row)}) Tj ET`);y-=size+5;}};const gap=(n=9)=>{y-=n;if(y<M+28)next();};const heading=(value:string)=>{gap(9);line(value,15,true);gap(3);};const s=data.summary;
 line("Reporte IA de iniciativas campesinas",23,true);line("ExpoInnovacion y CampeSENA",14,true);gap(18);line(`Fecha de generacion: ${new Date().toLocaleString("es-CO",{timeZone:"America/Bogota"})}`);line(`Total de iniciativas analizadas: ${s.analyzed}`);gap(30);line("ExpoSemilleros CAM IA",12,true);line("Reporte institucional consolidado",11);next();
 heading("1. Resumen general");line(`Total: ${s.total} | Analizadas: ${s.analyzed} | Pendientes: ${s.pending} | Con error: ${s.failed}`);line(`Alto potencial comercial: ${s.highPotential} | Prioridad alta: ${s.highPriority}`);line(`Genero explicito: ${s.explicitGender} | Mujeres involucradas: ${s.women} | Enfoque diferencial: ${s.differential}`);
 heading("2. Resumen por linea productiva");for(const x of data.byLine){line(x.linea,11,true);line(`Total ${x.total} | Analizadas ${x.analizadas} | Potencial predominante: ${x.potencial} | Prioridad: ${x.prioridad}`);line(`Riesgos: ${x.riesgos.join("; ")||"Sin datos"}`);line(`Oportunidades: ${x.oportunidades.join("; ")||"Sin datos"}`);gap(4);}
 heading("3. Potencial comercial, riesgos y oportunidades");line(`Potencial comercial: ${(data.charts.potencial||[]).map(x=>`${x.name}: ${x.value}`).join(" | ")||"Sin datos"}`);line(`Riesgos: ${(data.charts.riesgos||[]).map(x=>`${x.name} (${x.value})`).join("; ")||"Sin datos"}`);line(`Oportunidades: ${(data.charts.oportunidades||[]).map(x=>`${x.name} (${x.value})`).join("; ")||"Sin datos"}`);
 heading("4. Necesidades de fortalecimiento y recomendaciones");line(`Necesidades: ${(data.charts.necesidades||[]).map(x=>`${x.name} (${x.value})`).join("; ")||"Sin datos"}`);line(`Tendencias relacionadas: ${(data.charts.tendencias||[]).map(x=>`${x.name} (${x.value})`).join("; ")||"Sin datos"}`);
 heading("5. Inclusion, genero y enfoque diferencial");line(`Iniciativas con enfoque de genero explicito: ${s.explicitGender}`);line(`Iniciativas con mujeres involucradas explicitamente: ${s.women}`);line(`Iniciativas con enfoque diferencial explicito: ${s.differential}`);gap(8);line("El analisis se basa unicamente en informacion explicita registrada en las iniciativas campesinas. No se infiere genero ni enfoque diferencial a partir de nombres, apellidos, apariencia, municipio o institucion.",10,true);
 pages.forEach((commands,i)=>commands.push(`BT /F1 8 Tf 0 0 0 rg 1 0 0 1 278 24 Tm (Pagina ${i+1} de ${pages.length}) Tj ET`));const objects=["<< /Type /Catalog /Pages 2 0 R >>",`<< /Type /Pages /Kids [${pages.map((_,i)=>`${5+i*2} 0 R`).join(" ")}] /Count ${pages.length} >>`,"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>","<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>"];pages.forEach((commands,i)=>{const content=commands.join("\n");objects.push(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${W} ${H}] /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents ${6+i*2} 0 R >>`);objects.push(`<< /Length ${Buffer.byteLength(content,"latin1")} >>\nstream\n${content}\nendstream`);});let out="%PDF-1.4\n";const offsets=[0];objects.forEach((obj,i)=>{offsets.push(Buffer.byteLength(out,"latin1"));out+=`${i+1} 0 obj\n${obj}\nendobj\n`;});const xref=Buffer.byteLength(out,"latin1");out+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n${offsets.slice(1).map(o=>`${String(o).padStart(10,"0")} 00000 n `).join("\n")}\ntrailer\n<< /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return Buffer.from(out,"latin1");}
