import { z } from "zod";
import { callOpenRouter, type OpenRouterContentPart } from "@/lib/ai/openrouter";
import { toText, toTextArray } from "@/lib/ai/analysis-normalization";
import type { Project } from "@/types";

const score=z.coerce.number().catch(0).transform(v=>Math.min(100,Math.max(0,Math.round(v))));
const text=z.preprocess(v=>toText(v)||"No reportado explícitamente",z.string());
const list=z.preprocess(toTextArray,z.array(z.string()));
const evidenceLevel=z.preprocess(v=>{const value=toText(v);return ["Explícita","Parcial","No reportada explícitamente"].includes(value)?value:"No reportada explícitamente";},z.enum(["Explícita","Parcial","No reportada explícitamente"]));
const analysisSchema=z.object({
 resumen_ia:text,tendencias_identificadas:list,palabras_clave_ia:list,sectores_relacionados:list,nivel_innovacion_ia:score,nivel_pertinencia_ia:score,nivel_impacto_ia:score,nivel_viabilidad_ia:score,nivel_claridad_metodologica_ia:score,nivel_articulacion_tendencias_ia:score,riesgos_detectados:list,oportunidades_detectadas:list,puntaje_sugerido_ia:score,promedio_ia:score,porcentaje_ia:score,nivel_tendencia_ia:text,concepto_ia:text,
 enfoque_genero_ia:text,nivel_inclusion_genero_ia:text,mujeres_involucradas_ia:text,mujeres_en_formulacion_ia:text,mujeres_en_ejecucion_ia:text,evidencia_mujeres_involucradas_ia:text,evidencia_mujeres_formulacion_ia:text,evidencia_mujeres_ejecucion_ia:text,poblacion_impactada_ia:text,evidencia_poblacion_impactada_ia:text,brechas_genero_ia:list,acciones_genero_recomendadas_ia:list,recomendaciones_genero_ia:text,nivel_evidencia_genero_ia:evidenceLevel,
 enfoque_etnico_ia:text,nivel_inclusion_etnica_ia:text,recomendaciones_etnicas_ia:text,enfoque_diferencial_ia:text,grupos_diferenciales_identificados_ia:list,evidencia_enfoque_diferencial_ia:text,riesgos_exclusion_ia:list,oportunidades_inclusion_ia:list,nivel_evidencia_diferencial_ia:evidenceLevel,
});
export type TrendAnalysisResult=z.infer<typeof analysisSchema>&{modelo_ia:string;estado_analisis:"Completado";mensaje_error:string};
export type AnalysisFile={filename:string;mimeType:string;bytes:ArrayBuffer};
const scalar=(p:Project,k:keyof Project)=>typeof p[k]==="string"&&String(p[k]).trim()?String(p[k]).trim():"No registrado";
const multiple=(p:Project,k:keyof Project)=>Array.isArray(p[k])&&(p[k] as unknown[]).length?(p[k] as unknown[]).join(", "):"No registrado";
function extractJson(content:string){const candidate=content.trim().match(/```(?:json)?\s*([\s\S]*?)\s*```/i)?.[1]??content.trim();const first=candidate.indexOf("{");const last=candidate.lastIndexOf("}");if(first<0||last<=first)throw new Error("La IA no entregó un JSON válido.");try{return JSON.parse(candidate.slice(first,last+1));}catch{throw new Error("La IA no entregó un JSON válido.");}}
function trendLevel(p:number){if(p<=39)return "Bajo nivel de tendencia";if(p<=59)return "Tendencia emergente débil";if(p<=79)return "Tendencia emergente relevante";if(p<=89)return "Tendencia fuerte";return "Proyecto altamente tendencial";}

export async function analyzeProjectTrends(project:Project,file?:AnalysisFile,signal?:AbortSignal):Promise<TrendAnalysisResult>{
 const system=`Eres analista técnico de ExpoSemilleros CAM IA. Lee el archivo y los datos. Devuelve solo JSON válido. Analice inclusión, género y enfoque diferencial únicamente con base en evidencia explícita del proyecto. No infiera género por nombres propios, apellidos, municipio, institución, rol o apariencia. Para cada afirmación sobre mujeres involucradas, mujeres formuladoras, mujeres ejecutoras, población impactada o enfoque diferencial, incluya evidencia textual breve tomada de la información suministrada. Si no encuentra evidencia textual, responda "No reportado explícitamente". Los niveles de evidencia solo pueden ser "Explícita", "Parcial" o "No reportada explícitamente". Los campos lista siempre son arrays JSON y los puntajes están entre 0 y 100.`;
 const shape={resumen_ia:"",tendencias_identificadas:[],palabras_clave_ia:[],sectores_relacionados:[],nivel_innovacion_ia:0,nivel_pertinencia_ia:0,nivel_impacto_ia:0,nivel_viabilidad_ia:0,nivel_claridad_metodologica_ia:0,nivel_articulacion_tendencias_ia:0,riesgos_detectados:[],oportunidades_detectadas:[],puntaje_sugerido_ia:0,promedio_ia:0,porcentaje_ia:0,nivel_tendencia_ia:"",concepto_ia:"",enfoque_genero_ia:"",nivel_inclusion_genero_ia:"",mujeres_involucradas_ia:"",mujeres_en_formulacion_ia:"",mujeres_en_ejecucion_ia:"",evidencia_mujeres_involucradas_ia:"",evidencia_mujeres_formulacion_ia:"",evidencia_mujeres_ejecucion_ia:"",poblacion_impactada_ia:"",evidencia_poblacion_impactada_ia:"",brechas_genero_ia:[],acciones_genero_recomendadas_ia:[],recomendaciones_genero_ia:"",nivel_evidencia_genero_ia:"",enfoque_etnico_ia:"",nivel_inclusion_etnica_ia:"",recomendaciones_etnicas_ia:"",enfoque_diferencial_ia:"",grupos_diferenciales_identificados_ia:[],evidencia_enfoque_diferencial_ia:"",riesgos_exclusion_ia:[],oportunidades_inclusion_ia:[],nivel_evidencia_diferencial_ia:""};
 const prompt=`Analiza el proyecto y responde con esta estructura exacta: ${JSON.stringify(shape)}\nDatos registrados: ${JSON.stringify({nombre_proyecto:scalar(project,"nombre_proyecto"),linea_tematica:scalar(project,"linea_tematica"),semillero:scalar(project,"semillero"),municipio:scalar(project,"municipio"),resumen_problema:scalar(project,"resumen_problema"),resumen_objetivo:scalar(project,"resumen_objetivo"),resumen_metodologia:scalar(project,"resumen_metodologia"),resumen_resultados:scalar(project,"resumen_resultados"),resumen_conclusiones:scalar(project,"resumen_conclusiones"),productos_obtenidos:multiple(project,"productos_obtenidos"),nivel_madurez:scalar(project,"nivel_madurez"),roles:(project.equipo??[]).map(m=>m.rol_integrante)})}`;
 const content:OpenRouterContentPart[]=[{type:"text",text:prompt}];if(file)content.push({type:"file",file:{filename:file.filename,file_data:`data:${file.mimeType};base64,${Buffer.from(file.bytes).toString("base64")}`}});
 const response=await callOpenRouter([{role:"system",content:system},{role:"user",content}],{signal});const parsed=analysisSchema.parse(extractJson(response.content));const rubric=[parsed.nivel_innovacion_ia,parsed.nivel_pertinencia_ia,parsed.nivel_impacto_ia,parsed.nivel_viabilidad_ia,parsed.nivel_claridad_metodologica_ia,parsed.nivel_articulacion_tendencias_ia];const average=Math.round(rubric.reduce((s,n)=>s+n,0)/rubric.length);const percentage=Math.min(100,Math.max(0,parsed.porcentaje_ia||parsed.puntaje_sugerido_ia||average));return {...parsed,promedio_ia:average,porcentaje_ia:percentage,puntaje_sugerido_ia:parsed.puntaje_sugerido_ia||average,nivel_tendencia_ia:trendLevel(percentage),modelo_ia:response.modelUsed,estado_analisis:"Completado",mensaje_error:""};
}
