import { NextResponse } from "next/server";
import { z } from "zod";
import { isAdminAuthenticated } from "@/lib/admin-auth";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { analyzeAndSaveProductor } from "@/lib/ai/productores-analysis-service";
export const maxDuration=75;
const schema=z.union([z.object({action:z.literal("reset-stuck")}),z.object({action:z.literal("reset-errors")}),z.object({mode:z.enum(["pending","all","failed"]),limit:z.coerce.number().int().min(1).max(2).default(1),offset:z.coerce.number().int().min(0).default(0)})]);
async function metrics(db:ReturnType<typeof createSupabaseServerClient>){const [a,b,c]=await Promise.all([db.from("productores_iniciativas").select("id",{count:"exact",head:true}),db.from("productores_iniciativas").select("id",{count:"exact",head:true}).eq("estado_analisis_ia","Completado"),db.from("productores_iniciativas").select("id",{count:"exact",head:true}).eq("estado_analisis_ia","Error")]);return {total:a.count??0,analyzed:b.count??0,errors:c.count??0};}
export async function POST(request:Request){if(!(await isAdminAuthenticated()))return NextResponse.json({success:false,error:"No autorizado"},{status:401});try{const input=schema.parse(await request.json());const db=createSupabaseServerClient();if("action" in input){const states=input.action==="reset-errors"?["Error"]:["Procesando","En proceso","Analizando","En análisis"];const {data,error}=await db.from("productores_iniciativas").update({estado_analisis_ia:"Pendiente"}).in("estado_analisis_ia",states).select("id");if(error)throw error;return NextResponse.json({success:true,reset:data?.length??0,...await metrics(db),message:"Estados restablecidos a Pendiente."});}let query=db.from("productores_iniciativas").select("*",{count:"exact"}).order("created_at");if(input.mode==="failed")query=query.eq("estado_analisis_ia","Error");if(input.mode==="pending")query=query.or("estado_analisis_ia.is.null,estado_analisis_ia.eq.Pendiente");const {data,error,count}=await query.range(input.offset,input.offset+input.limit-1);if(error)throw error;const results=[];for(const row of data??[]){const result=await analyzeAndSaveProductor(db,row,{timeoutMs:60000});results.push(result);if(!result.success&&"paused" in result)break;}const completed=results.filter(r=>r.success).length;const paused=results.find(r=>!r.success&&"paused" in r);const failed=results.length-completed-(paused?1:0);const processed=completed+failed;const nextOffset=input.mode==="pending"?input.offset+failed:input.offset+processed;const m=await metrics(db);const remaining=input.mode==="pending"?Math.max(m.total-m.analyzed-m.errors,0):Math.max((count??0)-nextOffset,0);return NextResponse.json({success:true,processed,completed,failed,remaining,nextOffset,...m,lastProject:results.at(-1)?.code??null,rateLimited:Boolean(paused),errorType:paused?"OPENROUTER_RATE_LIMIT":null,logs:results.map(r=>r.success?`Completado ${r.code}`:`${"paused" in r?"Pausado":"Error"} ${r.code}: ${r.error}`)});}catch(error){return NextResponse.json({success:false,error:detail(error)},{status:500});}}
function detail(e:unknown){return e instanceof Error?e.message:"No se pudo procesar el lote.";}
